from setuptools import setup, find_packages

setup(
    name="medjepa",
    version="0.1.0",
    description="Self-Supervised Medical Image Representation Learning with JEPA",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Pratham Khija",
    url="https://github.com/prthmmkhija1/MedJEPA",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0",
        "torchvision>=0.15",
        "numpy",
        "pandas",
        "matplotlib",
        "scikit-learn",
        "pydicom",
        "nibabel",
        "monai",
        "albumentations",
        "opencv-python",
        "Pillow",
        "tqdm",
        "pyyaml",
    ],
    extras_require={
        "dev": [
            "pytest",
            "black",
            "flake8",
        ],
        "wandb": [
            "wandb",
            "tensorboard",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    entry_points={
        "console_scripts": [
            "medjepa-pretrain=scripts.pretrain:main",
            "medjepa-evaluate=scripts.evaluate:main",
        ],
    },
)
